server:
  port: 8080

spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 16379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000